# Generated by Django 2.2.7 on 2019-11-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191124_2106'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
