# Generated by Django 2.2.7 on 2019-11-24 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_justification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='justification',
            name='image',
            field=models.ImageField(null=True, upload_to=None),
        ),
    ]
