# Generated by Django 2.2.7 on 2019-11-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_justification_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='date',
            field=models.DateField(),
        ),
    ]
