# Generated by Django 2.2.7 on 2019-11-24 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20191124_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
