# Generated by Django 2.2.7 on 2019-11-24 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191125_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
