# Generated by Django 2.2.7 on 2019-11-25 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20191125_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='image',
            field=models.ImageField(default='', upload_to='img'),
        ),
    ]
