# Generated by Django 2.2.7 on 2019-11-24 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191125_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='image',
            field=models.ImageField(default='', upload_to='./img'),
        ),
    ]
