# Generated by Django 2.2.7 on 2019-11-25 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191125_1546'),
    ]

    operations = [
        migrations.RenameField(
            model_name='justification',
            old_name='Student',
            new_name='student',
        ),
    ]
