# Generated by Django 2.2.7 on 2019-11-25 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191125_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justification',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
